TOP=../..
include $(TOP)/configure/CONFIG

DB += example_sim.db

USES_TEMPLATE += $(LAKESHORE340)/db/lakeshore340.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

